### ISSUE TITLE
DataFrame to LASfile

### ISSUE THREAD

**Issue by dagrha** [kinverarity1/lasio#114]
The fact that lasio allows for easy manipulation via pandas is really fantastic (#94).

If this functionality doesn't already exist in lasio, it would be excellent if any changes that get applied to the `l.df` could be "pushed" back into the LASfile object.

That is, say for instance that I manipulate the `l.df` DataFrame object (in [the df notebook example](lasio/notebooks/using lasio with pandas DataFrame.ipynb), for example, `l.df.RES` is created), it could be useful to then "push" those changes back into the `LASfile.data` attribute, where it could be written out as an las file as needed.

**Comment by kinverarity1** [comment]
Yep - I think the best way for this to happen is that when using pandas, the ``data`` attribute should be replaced by a view into the dataframe. This will require some subtle dynamic generation of the ``curves`` attribute though.

In the meantime PR #115 (already in master) is an interim solution which works by checking the dataframe and updating the object, but only when the write() method is called.

**Comment by dagrha** [comment]
Very nice.  Thanks for adding this feature!

**Comment by kinverarity1** [comment]
Opening again for my reference - I need to implement a dynamically-selected view into df based on _use_pandas.

**Comment by kinverarity1** [comment]
Making a note for my own reference - getting this right is proving subtle and tricky.

There are several ways to access the same data at the moment

```
l['DT'] = ndarray
l.curves['DT'].data = ndarray
l.data[:, 2] = ndarray
l.df['DT'] = pd.Series
```

This all works fine until the user starts editing the ndarrays/pd.Series. I need to make sure ndarray views are being handled correctly so that the edits are reflected properly everywhere. And it gets more complicated now that pandas is involved  - What should happens when ``l.df['DT']`` gets re-indexed? Should the ``l['DEPT']`` ndarray be changed? Handling all this is tricky.

I am beginning to wonder if I need pandas as a dependency, and abandoning ndarray as the storage data type - but this is probably not good for larger LAS files. So maybe I need two ways of handling data in the background, depending on the use_pandas setting.

**Comment by kinverarity1** [comment]
Re previous comment - I have chosen to keep everything based on ndarrays and replace the ``LASFile.df`` attribute with a method ``LASFile.df()`` 

All previous functionality is still there. See this [explanation](https://github.com/kinverarity1/lasio/pull/128#issue-133410187).
