### ISSUE TITLE
Writing `string` values

### ISSUE THREAD

**Issue by roliveira** [kinverarity1/lasio#127]
I've ran into some troubles while trying to write `string` values in the **~ASCII** section. I'm not sure if this is supposed to be a `3.0` thing only, but I did a small PR #126 to approach this.

I would actually change the design a little bit more, specially to preserve the line spacing and would remove the `def format_data_section_line(...)` from inside the `write(...)` method.

**Comment by kinverarity1** [comment]
Non-numeric characters in the data section are only a LAS 3 feature but the PR works really well - I have merged it. Thank you!

I haven't added a unit test for this (writing non-numeric characters in the ~ASCII section) because the proper long-term functionality should be based on LAS 3 tests.

Also agree, the format_data_section_line doesn't belong there. The write() method needs work (and really belongs in a separate class).

**Comment by oliveirarodolfo** [comment]
So it wasn't actually a *fix* but a *new feature*! :smile: 

That's actually a plus and fit in the #120 issue. The `v1.2` does not **Text** support for the **~ASCII** section, but the `v1.2` does mention that is not supported, but not in a prohibitive manner:

> Other formats such as **Text** or Exponential values are not supported.

**Comment by kinverarity1** [comment]
Ah I see - remains to support reading text in though 😉

**Comment by kinverarity1** [comment]
I am adding v1 milestones for open issues which are related to supporting the LAS version 3 specification.

**Comment by kinverarity1** [comment]
I'll close this for now and continue any discussion of this feature (writing non-numeric characters in the data section) in #354.

**Comment by roliveira** [comment]
That's perfectly fine, my apologies for not following it closer.

**Comment by kinverarity1** [comment]
@roliveira all good, no problem at all. I was just cleaning up some old issues today.
