### ISSUE TITLE
add_curve() adds to all created objects

### ISSUE THREAD

**Issue by Dybov** [kinverarity1/lasio#141]
If I create new object LASFile as las1, then I create new object LASFile as las2, and then if I add curve to las1 via .add_curve() method it addes to both objects, but not to the object read from file.

**Comment by kinverarity1** [comment]
Thanks for this, I will look into it. Sounds like there could be a bug in there.



On Mon, Oct 24, 2016 at 9:19 PM +1030, "Andrew" <notifications@github.com<mailto:notifications@github.com>> wrote:


If I create new object LASFile as las1, then I create new object LASFile as las2, and then if I add curve to las1 via .add_curve() method it addes to both objects, but not to the object read from file.

-

**Comment by kinverarity1** [comment]
Thanks for this, bizarre behaviour! Looking into it.

**Comment by kinverarity1** [comment]
OK looks like inheriting list for las_items.SectionItems was a mistake. This can be fixed but will take a bit of time to reimplement that class.

**Comment by jgodwin** [comment]
The actual cause of the problem is that when a LASFile object is initialized, it inherits the default set of curves from a global dictionary from the defaults module that is shared between them.  When you add a curve, the curve goes into this global curve set, which is then automatically seen by the other LASFile because they actually reference the same set.  Solution:  make a copy of the default set when each LASFile is initialized.

**Comment by kinverarity1** [comment]
thanks!
