### ISSUE TITLE
NULL value replacing valid value in DEPT

### ISSUE THREAD

**Issue by kwinkunks** [kinverarity1/lasio#227]
Since DEPT is treated as a curve, I guess it gets clobbered by the NULL value:

![image](https://user-images.githubusercontent.com/1692372/37361438-a3bc78e0-26d1-11e8-908e-2350f31acebb.png)

I thought the default NULL value is -999.25, so maybe there are two problems here... Not sure.

I'm on version 0.19.

**Comment by kinverarity1** [comment]
Thanks for the report. 

Yes, lasio is considering 999.25 as a NULL in your case because of the default value for null_policy (``lasio.read(..., null_policy='common')`` - see the [documentation](http://lasio.readthedocs.io/en/latest/data-section.html#handling-invalid-data-indicators-automatically)). If you use ``null_policy='strict'`` that will fix your problem.

From a larger perspective this is tricky to fix because the replacements are done before wrapping is applied - see https://github.com/kinverarity1/lasio/blob/master/lasio/reader.py#L328. If I choose to ignore null substitutions for the first column, that's easy enough, but will only work for unwrapped files. I'd certainly welcome a PR that ignores all substitutions for the true first column in both wrapped and unwrapped files!

**Comment by VelizarVESSELINOV** [comment]
Suggestion to replace NULL after the reading of the file (wrapped or unwarapped) and skip the index column.

**Comment by kinverarity1** [comment]
Yes that would be ideal... PRs welcome ;-)

**Comment by kinverarity1** [comment]
FYI this is now fixed in `master`:

![image](https://user-images.githubusercontent.com/4525931/116016441-c3237080-a67b-11eb-899a-2f56c63531be.png)
