### ISSUE TITLE
las.write() rounding depths after 10000

### ISSUE THREAD

**Issue by dust10ingram** [kinverarity1/lasio#228]
Original Depth Array:
![depth1](https://user-images.githubusercontent.com/30836353/37434316-304f918a-27ad-11e8-84ff-2a881ca0158f.JPG)

Code:
![code](https://user-images.githubusercontent.com/30836353/37434663-4ba900c8-27ae-11e8-8c1b-e8d91122ea75.JPG)

.las File:
![depths2](https://user-images.githubusercontent.com/30836353/37434744-af2e89ba-27ae-11e8-8634-516e05cf325a.JPG)

**Comment by dagrha** [comment]
I think what is happening is the default number formatting in the lasio `writer.write()` method uses exponential formatting (e.g. 10000e+01) with 5 digit precision, so when it gets to depths with more than 5 total digits (e.g. 10,000.5) it cuts off the decimal.

Until this is fixed, you can try feeding the `fmt` kwarg to the `write()` method with something like `'%10.6g'` (rather than the default `%10.5g`), so it would be:
    
    with open(newlas, 'w') as f:
        m.write(f, fmt='%10.6g')

**Comment by kinverarity1** [comment]
Thanks! I've changed the default fmt to ``%.5f`` which should be more robust.

**Comment by VelizarVESSELINOV** [comment]
7g is my preferred option.
