### ISSUE TITLE
Reading large number of LAS files

### ISSUE THREAD

**Issue by dworley33** [kinverarity1/lasio#253]
Hello, I am new to python and having a hard time reading a large number of LAS files. I could load a single LAS file but could not figure how to load the whole folder at once. I researched online and could not find anything on this issue. I have all of the LAS files in a folder that I want to read. What is the best way to do this?

**Comment by kinverarity1** [comment]
Hi! There isn't a specific method in lasio for reading a whole folder of files at once, because it really depends on what you want to do with the files. Do you want to do something independently with each LAS file in turn, or do you want them all stored in memory at once?

For the first example:

```python
import glob
import lasio

for filename in glob.glob('*.las'):
    las = lasio.read(filename)
```

To store them all in memory, you might for example store them in a dictionary:

```python
import glob
import lasio

las_data = {}
for filename in glob.glob('*.las'):
    las = lasio.read(filename)
    las_data[filename] = las
```

These might help too:

- [Listing files in a directory](https://stackoverflow.com/questions/3207219/how-do-i-list-all-files-of-a-directory)
- [Using dictionaries to store things](http://www.compciv.org/guides/python/fundamentals/dictionaries-overview/)
