### ISSUE TITLE
What happens when periods are in both mnemonic and unit?

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#264]
```
~CURVE INFORMATION
DEPT.FT                   :DEPTH
Speed.M/MIN                   :Speed
Cond..MS/M                   :Cond.
Gamma.CPS                   :Gamma
I. Res..OHM-M                   :I. Res.
```

Currently parsed as:

```python
[CurveItem(mnemonic=DEPT, unit=FT, value=, descr=DEPTH, original_mnemonic=DEPT, data.shape=(1590,)),
 CurveItem(mnemonic=SPEED, unit=M/MIN, value=, descr=Speed, original_mnemonic=SPEED, data.shape=(1590,)),
 CurveItem(mnemonic=COND, unit=.MS/M, value=, descr=Cond., original_mnemonic=COND, data.shape=(1590,)),
 CurveItem(mnemonic=GAMMA, unit=CPS, value=, descr=Gamma, original_mnemonic=GAMMA, data.shape=(1590,)),
 CurveItem(mnemonic=I, unit=, value=Res..OHM-M, descr=I. Res., original_mnemonic=I, data.shape=(1590,))]
```

It is very difficult to figure out which period splits the mnemonic and unit, but at the very least we should be able to exploit the long whitespace to establish that the ``value`` is wrong for the last curve.

**Comment by RomCoch** [comment]
I don't know LAS1.2 specs but, according to LAS2.0 specs, line delimiters between mnemonic, units, value and description are "a) the first dot in a line, b) the first space after the first dot in a line c) the last colon in a line".
Dots shouldn't hence be used in the mnemonic...

**Comment by dcslagel** [comment]
After reviewing the September 1st, 1990, LAS1.2 spec, it doesn't seem to say anything about the first space after the first dot. However the examples seem to imply that the first space after the first dot delimits the unit field.

Here is a rough-draft algorithm for the ~CURVE section (which only has API numbers and spaces in the values field). 

In the ~CURVE section    
   While the next character after the first dot is a dot    
     then throw it away and consider the next character
    -example: 
      'Cond..MS/M' would get parsed to CurveItem(mnemonic=COND, unit=MS/M,...) 

  While the next character after dot-space '. ' is not a number character or a space
    then remove it from the value field and add it to the unit field (or throw it away). 
    -example: 
      'I. Res..OHM-M' would get parsed to CurveItem(mnemonic=I, unit=Res..OHM-M, value=, ...) 

Note: the 2nd 'while' statement isn't that good of a solution because the 'Res.' should be part of the mnemonic instead of part of the unit.  

DC

**Comment by kinverarity1** [comment]
For my own reference.

Attached is a LAS file which was exported from WellCAD 5.1 with a range of mnemonics and units containing periods and colons. It appears that the file prompting this issue was perhaps from an older version of the software, because this version replaces all of the periods in mnemonics with underscores. However, it retains periods in units:

```
~CURVE INFORMATION
DEPT.M                   :DEPTH
APP__IND_.MS/M           :APP. IND.
TEMP_.'C                 :Temp.
RES_.OHM.M               :RES.
ROLL_3#1.DEG             :Roll:3#1
TILT.DEG.                :Tilt
```
[wellcad_unit_parsing_2.zip](https://github.com/kinverarity1/lasio/files/4119756/wellcad_unit_parsing_2.zip)
