### ISSUE TITLE
[request] - Add support for borehole images

### ISSUE THREAD

**Issue by manuelblancovalentin** [kinverarity1/lasio#284]
Even though it is possible to use lasio to import borehole images, it requires an extra step of post-processing to merge all channels with the same mnemonic together, which is undesirable.

I.e, a certain borehole image (such as the raw amplitude from a UBI tool) might have N cols (thus ranging from AWBK[0] to AWBK[N]). If I'm not mistaken, currently your code recognizes these entries as separate logs, so it's required to merge them after importation.

It would be awesome If you could just detect that AWBK[0] and AWBK[i] belong to the same log.

Thanks!

**Comment by manuelblancovalentin** [comment]
Btw, I am not sure how difficult that is to implement right now, but I'd be more than happy to contribute and maybe fix this issue, If you wish so.

**Comment by ThomasMGeo** [comment]
It's super hard to do, look into https://github.com/equinor/dlisio

**Comment by kinverarity1** [comment]
This is definitely something we should do - I've seen those kind of files before for broadband sonic.

I'll have a think about the API but implementing it is easy, just index the LASFile.data ndarray with a list instead of a integer.
________________________________

**Comment by dagrha** [comment]
Would making this a method of the LASFile object make any sense (rather than doing it automatically on read)? Something like `las.concatenate_channels()`.

It would be straightforward to do the columns-to-array operation(s) on a DataFrame (`las.df()`), then set again with the `set_data_from_df()` method. 

Maybe the array would get dropped on write (since those aren't part of LAS 1.2/2 spec...or maybe they are?), in other words only the AWBK[1] etc. channels would get written

**Comment by kinverarity1** [comment]
A method makes sense to me, yeah. I prefer "curve" to "channel". Also I wonder if `las.concatenate()` might confuse with anyone trying to join two LAS files together (e.g. `pd.concat()`). Would `las.stack_channels()` or just `las.stack()` make sense? Returning a 2D ndarray.

The LAS file object itself would stay unaffected, since I'm pretty sure in the specs curves can only be 1D.

We could do it on the dataframe but probably also just using indexing on `las.data`, using the indices of each curve e.g. `las.data[:, np.array([3,4,...,103])]` if the first three columns were not part of the image.

**Comment by dagrha** [comment]
Those are all good points. I'd be happy to take a stab at adding this feature.

**Comment by dagrha** [comment]
@manuelblancovalentin, i don't frequently work with image logs, so it's not obvious to me what kind of processing should be done on the multi-channel curves. What datatype are you wanting from this? What specifically should it look like? What I've got working now spits out a 2D ndarray, as suggested by kinverarity1, each row as simply an array of the values of AWBK[1] through AWBK[n]

**Comment by manuelblancovalentin** [comment]
When I tested your code I tried importing a borehole image but I did not got a single 2d nd.array as output. Instead I got 180 single vectors, one for each column of the borehole image (AWBK in this specific case, which ranged from AWBK[0] to AWBK[179]). I was simply asking for a single 2d output for the whole AWBK channel.

I might be mistaken tho. It's been a long time since I opened this thread.

**Comment by ThomasMGeo** [comment]
Can you share a notebook and data file? @manuelblancovalentin

**Comment by dagrha** [comment]
Oh sorry for the confusion! I've been working on a local branch, not yet merged here! I'm working on adding some tests before i submit a PR

**Comment by kinverarity1** [comment]
Thanks to @dagrha this has been implemented in master via #293 :tada:
