### ISSUE TITLE
Add a bit more to 'Example session' in README

### ISSUE THREAD

**Issue by kwinkunks** [kinverarity1/lasio#336]
The README seems to skip over the creation of the `las` object.

**Comment by kinverarity1** [comment]
Thanks for the feedback @kwinkunks!

I have been trying to keep the readme short because maintaining it is a pain but I can fill any obvious gaps. 

At the bottom it does mention that building LAS files is covered in the docs - is that what you are referring to? E.g. see

https://lasio.readthedocs.io/en/latest/building.html

There's a rewrite of the documentation sitting in an unmerged branch too 😣

**Comment by kinverarity1** [comment]
Fixed in 04de4fe
