### ISSUE TITLE
LAS conformity checkup

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#46]
A lot of people would like to have good working LAS certify solution.

If you can add a function that read the file and strictly check all the readings and return True or False will be a great addition for all the data managers.

If you can push the dream of all data managers is to add LAS repair functionality take a LAS with some strange formatting and convert it to a LAS that can be readable by all the packages.

**Comment by kinverarity1** [comment]
Shouldn't be too hard for 1.2 and 2.0 -- could be a nightmare for v3.

**Comment by VelizarVESSELINOV** [comment]
You can start with 1.2 and 2.0, most of LAS files with issues are before v3 :)

**Comment by kinverarity1** [comment]
I am picturing the API for this as at least a few methods on ``LASFile``:

1. ``check_conforming()`` - returns True or False.
2. ``to_conforming()`` - returns a LASFile object which does conform to the standard.
3. ``conformity()`` - I'm sure there's a better name for this. It would return some form of custom object, probably whatever is used for (2) - i.e. a list of situations where the file does not meet the specification in some way, and a way to modify the file so that it does.

Other than that, any help is welcome!

**Comment by kinverarity1** [comment]
Thanks @MandarJKulkarni for submitting a PR #283.

I'd like to work towards what's outlined here as a feature before merging - let me know if you need some guidance, I have an idea about how to structure it.

**Comment by MandarJKulkarni** [comment]
Thanks Kent, I agree with your points, I'll make the corresponding changes.

**Comment by kinverarity1** [comment]
I'm closing this issue now, as we have explored an approach in #283 and [decided](https://github.com/kinverarity1/lasio/pull/283#issuecomment-576466117) that it is beyond lasio's scope.
